name: "Solarman Logger"
description: "Read Deye Inverter stats from solarman wifi logger. Reworked by https://github.com/tamato27/Deye"
version: "1.0"
slug: "deye_logger_addon"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  inverter_ip: null
  inverter_port: 8899
  inverter_sn: null
  mqtt: false
  mqtt_server: null
  mqtt_port: 1883
  mqtt_topic: /deye
  mqtt_username: null
  mqtt_passwd: null
schema:
  inverter_ip: str
  inverter_port: int
  inverter_sn: str
  mqtt: bool
  mqtt_server: str?
  mqtt_port: int?
  mqtt_topic: str?
  mqtt_username: str?
  mqtt_passwd: str?
